name: urovo_pos
description: Flutter plugin for Urovo POS (Android), starting with printer APIs and modular feature expansion.
version: 0.1.0

repository: https://github.com/ParhamHatan/Urovo-POS-Flutter
issue_tracker: https://github.com/ParhamHatan/Urovo-POS-Flutter/issues

topics:
  - pos
  - printer
  - urovo
  - android

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.urovo.pos.urovo_pos
        pluginClass: UrovoPosPlugin
